.TH qkdisplays 1 "2025-06-18" "qkdisplays 1.0" "User Commands"
.SH NAME
qkdisplays \- Quick Displays
.SH SYNOPSIS
.B qkdisplays
[
.I OPTIONS
]
.I COMMAND
[
.I ARGS
]
.SH DESCRIPTION
.PP
.B qkdisplays
is a helper tool for quickly configuring a multi-monitor setup, built with tiled window managers in mind. Useful if you often change your multi-monitor setup and wish to configure it with the same ease you navigate your window manager.
.PP
At the moment qkdisplays only supports Sway but support for other environments might be added in the future.
.SH USAGE
.PP
qkdisplays provides multiple commands that can control the positioning of the displays (as well as scaling). The idea is that you can configure Sway to add keybindings for each of these commands (most likely in its own separate mode). You can check out the \fBSWAY CONFIG EXAMPLE\fR section later in this document.
.PP
Running \fBqkdisplays show\fR (which you can run when you enter the Sway mode) will show a 1-indexed numbered indicator on each display, going from left to right. E.g., the display that shows 1 is configured to be the leftmost display. You can use this to quickly tell how the displays are currently configured. Then, you can use \fBqkdisplays focus\fR to navigate using these indicators, \fBqkdisplays place\fR to move displays using these indicators or \fBqkdisplays move\fR to switch between a display and the one adjacent to it to its right or left. Finally, \fBqkdisplays close\fR closes these indicators (which you can run upon exiting the Sway mode).
.PP
\fBNOTE:\fR At the moment qkdisplays only supports configuring the positions of the displays on the x axis, and pretty much expects you to have a setup where all the displays are contiguous on that axis (you can even enforce them to all be on the same position on the y axis with the \fBstrict_y\fR config option). This is because A. the idea of this tool is to quickly configure the displays which might not be the case if the options are too complex and B. I have to admit that I personally only want this setup, and never actually found use for a case where the displays are not all contiguous on the x axis.
.PP
qkdisplays also supports setting the scaling of the currently focused display using \fBqkdisplays set_scale\fR.
.SH OPTIONS
.TP
.B \-\-allow-reorg, \-\-no-allow-reorg
Allow qkdisplays to move displays to be contiguous from left to right if they are not already are. If this is not set and the displays are not already contiguous then qkdisplays will fail.
.TP
.B \-\-strict-y, \-\-no-strict-y
All displays should have the same position on the Y axis. If they are not then if allow_reorg is set qkdisplays will move them to be so, otherwise it will fail.
.TP
.B \-\-config \fIPATH\fP
Specifies a config file.
.SH COMMANDS
.TP
.B show
Show a pop up on each display with a number. These numbers should be according to the order of the displays, starting from 1 and going from left to right. These numbers can quickly tell you the positions of the different displays, and can be used to identify a display using commands such as 'focus' or 'place'. To close the pop ups, run 'qkdisplays close'.
.TP
.B close
Close a running 'qkdisplays show'.
.TP
.B move \fIdirection\fP
Move the currently focused display to the specified direction.
\fIdirection\fP can be 'left' or 'right'.
.TP
.B focus \fIdisplay_number\fP
Focus on the display specified by \fIdisplay_number\fP (1-indexed).
.TP
.B place \fIdisplay_number\fP
Replace the currently focused display with the one specified by \fIdisplay_number\fP (1-indexed).
.TP
.B refresh
Normally a running 'qkdisplays show' will only refresh its pop ups in case the displays were moved through the qkdisplays tool. This command explicitly asks qkdisplays to refresh the pop ups, which can be useful if you moved the displays through another tool.
.TP
.B set_scale \fIscale\fP
Set the scale of the currently focused display. Can be an absolute value (e.g., "1.5") or a relative change (e.g., "+0.2", "-0.1").
.SH CONFIGURATION
.PP
.B qkdisplays
can be configured via a JSON file. The utility searches for a configuration file in the following order:
.RS
.IP \(bu 2
.B File supplied using command line via --config
.IP \(bu 2
.B $XDG_RUNTIME_DIR/qkdisplays.json
.IP \(bu 2
.B $HOME/.config/qkdisplays.json
.IP \(bu 2
.B /etc/qkdisplays.json
.RE
.PP
The configuration file should be a JSON object with keys corresponding to the options, e.g.,
.nf
.RS
.PP
.B { 'allow_reorg': false, 'strict_y': true }
.RE
.fi
.PP
Command-line arguments override settings from the configuration file.
.SH EXAMPLES
.TP
.B qkdisplays show
Display numbered pop-ups on all active monitors.
.TP
.B qkdisplays move right
Move the currently focused display one position to the right.
.TP
.B qkdisplays focus 2
Focus on the second display from the left.
.TP
.B qkdisplays place 1
Swap the currently focused display with the first display.
.TP
.B qkdisplays set_scale +0.2
Increase the scale of the focused display by 0.2.
.TP
.B qkdisplays set_scale 1.25
Set the scale of the focused display to 1.25.
.TP
.B qkdisplays --no-allow-reorg show
Show indicators, but fail if displays are not contiguous.
.SH SWAY CONFIG EXAMPLE
.nf
mode "monitors" {
    # In monitors mode navigate between monitors same as you would normally in
    # sway between containers/workspaces, except no up/down and no $mod key.

    bindsym $left focus output left
    bindsym $right focus output right

    bindsym Shift+$left exec qkdisplays move left
    bindsym Shift+$right exec qkdisplays move right

    bindsym 1 exec qkdisplays focus 1
    bindsym 2 exec qkdisplays focus 2
    bindsym 3 exec qkdisplays focus 3
    bindsym 4 exec qkdisplays focus 4
    bindsym 5 exec qkdisplays focus 5
    bindsym 6 exec qkdisplays focus 6
    bindsym 7 exec qkdisplays focus 7
    bindsym 8 exec qkdisplays focus 8
    bindsym 9 exec qkdisplays focus 9
    bindsym 0 exec qkdisplays focus 10

    bindsym Shift+1 exec qkdisplays place 1
    bindsym Shift+2 exec qkdisplays place 2
    bindsym Shift+3 exec qkdisplays place 3
    bindsym Shift+4 exec qkdisplays place 4
    bindsym Shift+5 exec qkdisplays place 5
    bindsym Shift+6 exec qkdisplays place 6
    bindsym Shift+7 exec qkdisplays place 7
    bindsym Shift+8 exec qkdisplays place 8
    bindsym Shift+9 exec qkdisplays place 9
    bindsym Shift+0 exec qkdisplays place 10

    # Configure scale of current output with + and -
    bindsym plus exec qkdisplays set_scale +0.05
    bindsym minus exec qkdisplays set_scale -0.05
    # Restore scale to 1 with =
    bindsym equal exec qkdisplays set_scale 1

    # Close qkdisplays, return to default mode
    bindsym Return exec qkdisplays close; mode "default"
    bindsym Escape exec qkdisplays close; mode "default"
}
# Have qkdisplays running while in monitors mode to show monitor indications
bindsym $mod+Shift+m exec qkdisplays show; mode "monitors"
.fi
.SH AUTHORS
Tamir Zahavi-Brunner
